<?php
/**
 * @file
 * Gedparse dynamically generates genealogy web pages from a GEDCOM file.
 */


/**
 * Implements hook_help().
 */
function gedparse_help($path, $arg) {
  if ($path == 'admin/help#Gedparse') {
    return t('Gedparse dynamically generates genealogy web pages from a GEDCOM file.');
  }
}

/**
 * Implements hook_menu().
 */
function gedparse_menu() {
  $items = array();

  $items['admin/config/Gedparse'] = array(
    'title' => 'Configure Gedparse',
    'description' => 'Configure settings for the Gedparse module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gedparse_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['family/%'] = array(
    //'title' => t('Family Tree Info'),
    'page callback' => 'gedparse_display_person',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Callback function to create the admin config page.
 */
function gedparse_admin() {
  $form = array();

  $form['gedparse_db_location'] = array(
    '#type' => 'textfield',
    '#title' => t('Location of your GEDCOM file'),
    '#size' => 100,
    '#maxlength' => 100,
    '#description' => t('This directory should not be accessible over the web.'),
    '#default_value' => variable_get('gedparse_db_location'),
    '#required' => TRUE,
  );

  $form['gedparse_headshot_location'] = array(
    '#type' => 'textfield',
    '#title' => t('Location of your optional folder of headshots'),
    '#size' => 100,
    '#maxlength' => 100,
    '#description' => t('This directory must be accessible over the web.'),
    '#default_value' => variable_get('gedparse_headshot_location'),
  );

  // allow admin to set permissions?

  return system_settings_form($form);
}

/**
 * Callback function to display a person.
 */
function gedparse_display_person($indi_number) {
  // set up array for later output
  $gedparse_event_list = array(
    'BIRT' => 'Born',
    'CHR'  => 'Christened',
    'DEAT' => 'Died',
    'BURI' => 'Buried',
    'CREM' => 'Cremated',
    'ADOP' => 'Adopted',
    'BAPM' => 'Baptized',
    'BARM' => 'Bar Mitzvah',
    'BASM' => 'Bas Mitzvah',
    'BLES' => 'Blessing given',
    'CHRA' => 'Christened as adult',
    'CONF' => 'Confirmed',
    'FCOM' => 'First Communion',
    'ORDN' => 'Ordained',
    'NATU' => 'Naturalized',
    'EMIG' => 'Emigrated',
    'IMMI' => 'Immigrated',
    'CENS' => 'Census record',
    'PROB' => 'Probate',
    'WILL' => 'Will',
    'GRAD' => 'Graduated',
    'RETI' => 'Retired',
    'EVEN' => '',
    'CAST' => 'Caste',
    'DSCR' => 'Description',
    'EDUC' => 'Scholastic achievment',
    'IDNO' => 'National ID #',
    'NATI' => 'Nationality',
    'NCHI' => 'No. of children',
    'NMR'  => 'No. of marriages',
    'OCCU' => 'Occupation',
    'PROP' => 'Possessions',
    'RELI' => 'Religion',
    'RESI' => 'Residence',
    'SSN'  => 'SSN#',
    'TITL' => 'Title'
  );

  // get the raw data
  $flat_record = gedparse_get_record('INDI', $indi_number) ;

  // Explode flat_record to get array of separate items
  $items = explode("\n1 ", $flat_record) ;

  // create some variables for each kind of item
  $gender = '' ;

  // Records are not restricted by default
  $restricted = FALSE ;

  $parents = array() ;
  $names = array() ;
  $events = array() ;
  $notes = array() ;
  $links = array() ;
  $partners = array() ;
  $siblings = array() ;

  // iterate through all the record items, sorting into the arrays and
  // theming if necessary
  foreach ($items as $item) {
    if (strpos($item, '@') === 0) {
      // only here so we can use 'else' at end as a catch-all bucket
    }

    elseif (strpos($item, 'RESN') === 0) {
      $restricted = TRUE ;
    }

    elseif (strpos($item, 'FAMC') === 0) {
      preg_match('@F(\d+)@i', $item, $matches);

      $parent_id_numbers = gedparse_get_family_members($matches[1], 'parents') ;

      foreach ($parent_id_numbers as $id_number) {
        $parent = gedparse_person_link($id_number) ;

        $parents[] = $parent ;
      }

      $sibling_id_numbers = gedparse_get_family_members($matches[1], 'siblings', $indi_number) ;

      foreach ($sibling_id_numbers as $id_number) {
        $sibling = gedparse_person_link($id_number) ;

        $siblings[] = $sibling ;
      }
    }

    elseif (strpos($item, 'FAMS') === 0) {
      preg_match('@F(\d+)@i', $item, $matches);

      $partner_id_numbers = gedparse_get_family_members($matches[1], 'partners', $indi_number) ;

      foreach ($partner_id_numbers as $id_number) {
      $partner = gedparse_person_link($id_number) ;

      $partners[] = $partner ;
      }
    }

    elseif (strpos($item, 'SSN') === 0) {
      $events[] = array(
        '#theme' => 'gedparse_event',
        '#label' => 'SSN#',
        '#info' => substr($item, 3),
      ) ;
    }

    elseif (strpos($item, 'SEX') === 0) {
      $gender = substr($item, 3) ;
    }

    elseif (strpos($item, 'NAME') === 0) {
      // need to run through clean_names
      $name = array(
        '#theme' => 'gedparse_name',
        '#html_open' => NULL,
        '#html_close' => NULL,
        '#npfx' => NULL,
        '#full_name' => NULL,
        '#nsfx' => NULL,
        '#nick' => NULL,
        '#notes' => NULL,
      ) ;

      $name_parts = explode("\n2 ", $item) ;

      foreach ($name_parts as $part) {
        if (strpos($part, 'NPFX') === 0) {
          $name['#npfx'] = substr($part, 4) ;
        }

        elseif (strpos($part, 'NAME') === 0) {
          $name['#full_name'] = substr($part, 4) ;
        }

        elseif (strpos($part, 'NSFX') === 0) {
          $name['#nsfx'] = substr($part, 4) ;
        }

        elseif (strpos($part, 'NICK') === 0) {
          $name['#nick'] = substr($part, 4) ;
        }

        elseif (strpos($part, 'NOTE') === 0) {
          $name['#notes'] = array(
            '#theme' => 'item_list',
            '#type' => 'ul',
            '#items' => gedparse_concatenate(substr($part, 4)),
          ) ;
        }
      }

      $names[] = $name ;
    }

    elseif (strpos($item, 'NOTE') === 0) {
      $notes[] = gedparse_concatenate(substr($item, 4)) ;
    }

  elseif (strpos($item, 'OBJE') === 0) {
    $obje = array(
      'href' => NULL,
      'title' => NULL,
    ) ;

    $item_parts = explode("\n2 ", $item) ;

    foreach ($item_parts as $part) {
        if (strpos($part, 'FILE') === 0) {
          $obje['href'] = substr($part, 4) ;
        }

        elseif (strpos($part, 'TITL') === 0) {
          $obje['title'] = substr($part, 4) ;
        }
      }

      $links[] = $obje ;
    }

    else {
      $event = array(
        '#theme' => 'gedparse_event',
        '#type' => NULL,
        '#date' => NULL,
        '#plac' => NULL,
        '#notes' => NULL,
        '#caus' => NULL,
        '#info' => NULL,
        '#notes' => array(
          '#theme' => 'item_list',
          '#type' => 'ul',
          '#items' => NULL,
        ),
      ) ;

    $item_parts = explode("\n2 ", $item) ;

    $event['#label'] = $gedparse_event_list[array_shift($item_parts)] ;

      foreach ($item_parts as $part) {
        if (strpos($part, 'TYPE') === 0) {
          if ($event['#label'] == 'Occupation') {
            $event['#info'] = substr($part, 4) ;
          }

          else {
            $event['#type'] = substr($part, 4) ;
          }
        }

        elseif (strpos($part, 'DATE') === 0) {
          $event['#date'] = substr($part, 4) ;
        }

        elseif (strpos($part, 'PLAC') === 0) {
          $event['#plac'] = substr($part, 4) ;
        }

        elseif (strpos($part, 'CAUS') === 0) {
          $event['#caus'] = substr($part, 4) ;
        }

        elseif (strpos($part, 'NOTE') === 0) {
          $event['#notes']['#items'][] = gedparse_concatenate(substr($part, 4)) ;
        }
      }

      $events[] = $event ;
    }
  }

  // need to change the first name item to be a header
  $names[0]['#html_open'] = '' ;
  $names[0]['#html_close'] = '' ;

  // now theme the first name and use the rendered HTML for the title
  $title = drupal_render($names[0]) ;

  drupal_set_title($title) ;

  // need to unset the #printed and #children flags after rendering
  // since we will use $names[0] again; also need
  // to set the first name item to be a header
  unset($names[0]['#printed']) ;
  unset($names[0]['#children']) ;
  $names[0]['#html_open'] = '<h2>' ;
  $names[0]['#html_close'] = '</h2>' ;

  $output =  array(
   'gender' => array(
      '#type' => 'markup',
      '#markup' => $gender,
      '#prefix' => '<p>Gender: ',
      '#suffix' => '</p>',
    ),
   'parents' => array(
      '#theme' => 'links',
      '#heading' => t('Parents'),
      '#links' => $parents,
    ),
  'headshot' => array(
      '#theme' => 'image',
      // should use configured folder location
      '#path' => 'sites/etgdesign.com/files/headshots/indi' . $indi_number . '.jpg',
      '#width' => '75px',
      '#height' => '100px',
      '#alt' => 'Portrait of ' . $title ,
    ),
    'names' => $names,
    'events' => $events,
  ) ;

  if ($notes) {
    $output['notes'] = array(
      '#theme' => 'item_list',
      '#title' => t('Notes'),
      '#type' => 'ul',
      '#items' => $notes,
    ) ;
  }

  if ($links) {
    $output['links'] = array(
      '#theme' => 'links',
      '#heading' => t('Related Links'),
      // should be h3, not h2
      '#links' => $links,
    ) ;
  }

  if ($partners) {
    $output['partners'] = array(
      '#theme' => 'links',
      '#heading' => t('Partners'),
      '#suffix' => t('<p class="partner-disclaimer">(Select a partner to display information on their union)</p>'),
      '#links' => $partners,
    ) ;
  }

  if ($siblings) {
    $output['siblings'] = array(
      '#theme' => 'links',
      '#heading' => t('Siblings'),
      '#links' => $siblings,
    ) ;
  }

// only for debugging purposes
//  $output['items'] = array(
//    '#theme' => 'item_list',
//    '#title' => t('Items'),
//    '#type' => 'ul',
//    '#items' => $items,
//  ) ;

// only for debugging purposes
//    $output['whole_record'] = array(
//       '#type' => 'markup',
//       '#markup' => $flat_record,
//       '#prefix' => '<pre>',
//       '#suffix' => '</pre>',
//    ) ;

  return $output;
}

/**
 * Validate the user-entered Gedparse settings.
 */
function gedparse_admin_validate($form, &$form_state) {
  $gedparse_db_location = $form_state['values']['gedparse_db_location'];
  if (!file_exists($gedparse_db_location)) {
    form_set_error('gedparse_db_location', t("Can't find a file at that location."));
  }

  $gedparse_headshot_location = $form_state['values']['gedparse_headshot_location'];
  if ($gedparse_headshot_location && !file_exists($gedparse_headshot_location)) {
    form_set_error('gedparse_headshot_location', t("Can't find a folder at that location."));
  }
}

/**
 * Implements hook_theme().
 */
function gedparse_theme() {
  return array(
    'gedparse_event' => array(
      'variables' => array(
        'label' => NULL,
        'type' => NULL,
        'date' => NULL,
        'plac' => NULL,
        'info' => NULL,
        'notes' => NULL,
        'caus' => NULL,
      ),
    ),

    'gedparse_name' => array(
      'variables' => array(
        'html_open' => '<p><em>(',
        'html_close' => ')</em></p>',
        'npfx' => NULL,
        'full_name' => NULL,
        'nsfx' => NULL,
        'nick' => NULL,
        'notes' => NULL,
      ),
    ),
  );
}

/**
 * Custom theme function for event items
 */
function theme_gedparse_event($variables) {
  $output = "\n\n<p><em>" ;

  if ($variables['label'] && $variables['type']) {
    $output .= $variables['label'] . '</em> ' . $variables['type'] . "<br>\n";
  }

  elseif ($variables['label']) {
    $output .= $variables['label'] . '</em> ';
  }

  elseif ($variables['type']) {
    $output .= $variables['type'] . '</em> ';
  }

  if ($variables['info']) {
    if (strpos($variables['info'], 'Y') === 0) {
      $output .= 'Yes';
    }

    else {
      $output .=  $variables['info'] ;
    }
  }

  if ( $variables['info'] && ($variables['plac'] || $variables['date']) ) {
    $output .= ', ' ;
  }

  if ($variables['date']) {
    $output .= $variables['date'] ;
  }

  if ($variables['date'] && $variables['plac']) {
    $output .= '; ' ;
  }

  if ($variables['plac']) {
    $output .= $variables['plac'] ;
  }

  if ($variables['caus']) {
    $output .= "<br>\n<em>Cause:</em>" . $variables['caus'] ;
  }

  $output .= '</p>' ;

  // Also get Drupal to render HTML for a list of notes
  $output .= drupal_render($variables['notes']) ;

  return $output ;
}


/**
 * Custom theme function for names
 */
function theme_gedparse_name($variables) {
  // build the name by checking for each part in the array and adding
  // to the output string

  $output = "\n\n" . $variables['html_open'] ;
  $output .= $variables['npfx'] ? $variables['npfx'] : '' ;
  $output .= $variables['full_name'] ? gedparse_clean_name($variables['full_name']) : 'Name unknown' ;
  $output .= $variables['nsfx'] ? ', ' . $variables['nsfx'] : '' ;
  $output .= $variables['nick'] ? ', “' . $variables['nick'] . '”' : '' ;
  $output .= $variables['html_close'] ;

  // Also get Drupal to render HTML for a list of notes
  $output .= drupal_render($variables['notes']) ;

  return $output ;
}

  /**
  * Custom theme function for a person's name that links to their record
  */
  function gedparse_person_link($id_number) {
    $record = gedparse_get_record('INDI', $id_number) ;

    $person_link = array(
      'href' => 'family/' . $id_number ,
    ) ;

    // check if the person's record is restricted
    $privacy = strpos($record, 'RESN privacy') ;
    if ($privacy !== FALSE) {
      $person_link['title'] = 'Name withheld' ;
    }

    else {
      preg_match('~1 NAME (.+?)$~m', $record, $matches) ;
      $name = $matches ? $matches[1] : 'Name unknown' ;

      preg_match('~^1 BIRT[^\n1]*\n2 DATE .*?(\d{4})~ms', $record, $matches) ;
      $birth = $matches ? $matches[1] : ' ' ;

      preg_match('~^1 DEAT[^\n1]*\n2 DATE .*?(\d{4})~ms', $record, $matches) ;
      $death = $matches ? $matches[1] : ' ' ;

      $person_link['title'] = gedparse_clean_name($name) ;
      $person_link['title'] .= ' (' . $birth . '–' . $death . ')' ;
    }

    return $person_link ;
  }

/**
 * Get an exploded array of records from the flat GEDCOM file.
 *
 * Use Drupal's Cache API to improve performance.
 */
function gedparse_get_all_records() {


  // First check if the exploded array is already cached.
  // If not, create and cache it.
  if (!$all_records = cache_get('Gedparse:all_records', 'cache')) {
    // The user should have set this location in /admin/config/Gedparse
    $file = variable_get('gedparse_db_location') ;

    // Display a custom error message and redirect to home page
    // if the GEDCOM file can't be found.
    try {
      $fh = fopen($file, 'r') ;

      if ($fh === FALSE) {
        throw new Exception('Cannot open GEDCOM file') ;
      }
    }

    catch (Exception $e) {
      drupal_set_message(t('Cannot open GEDCOM file! Please check Gedparse configuration.'), 'warning') ;
      drupal_goto() ;
    }

    // Read the entire file
    $gedcom = fread($fh, filesize($file));
    fclose($fh);

    // Then split the file into an array of records
    $all_records = explode("\n0 ", $gedcom);

    // Cache the array
    cache_set('Gedparse:all_records', $all_records, 'cache', CACHE_TEMPORARY) ;

    // And return it
    return $all_records ;
  }

  // If it IS in the cache, get it
  else {
    $all_records = cache_get('Gedparse:all_records', 'cache') ;

    // need to check if expired? See comment-48288 on cache_get API page
    // And return the data value of the cached item
    return $all_records->data ;
  }
}

/**
 * Retrieve an INDI or FAM record from exploded array of the flat GEDCOM file.
 *
 * Use Drupal's Cache API to improve performance.
 */
function gedparse_get_record($type, $record_number) {
  $all_records = gedparse_get_all_records() ;

  $matches = preg_grep('/^@[IF]' . $record_number . '@ ' . $type . '/', $all_records) ;

  // by default, preg_grep retains the input array's keys, so need to reset keys.
  $matches = array_values($matches) ;

  return $matches[0] ;
}


/**
 * Retrieve the INDI numbers of all members for a given family
 *
 * Takes a family id number as 1st argument
 * Takes a relationship (parent, spouse, sibling) as 2nd argument
 * Takes the selected person's id number as an optional 3rd arg
 *
 * Returns an array of the partners' id numbers
 */
function gedparse_get_family_members($family_number, $relationship, $selected_person = NULL) {
  // init an array to hold the spouse id numbers
  $family_members = array() ;

  $family_record = gedparse_get_record('FAM', $family_number) ;
  $family_parts = explode("\n1 ", $family_record) ;

  foreach ($family_parts as $person) {
    if ($relationship == 'parents' || $relationship == 'partners') {
      preg_match("~[HUSB|WIFE] @I(\d+)@~", $person, $matches) ;
    }

    // if not parents or partners, must be siblings
    else {
      preg_match("~[CHIL] @I(\d+)@~", $person, $matches) ;
    }

    // if we found family members...
    if ($matches) {
      // only add them to array if either: (1) we didn't pass an id number
      // [which means we're looking for parents, so want both]
      // of (2) the id number arg isn't the same as the family member
      // [because we we're looking for partners or siblings]
      if (!$selected_person || $selected_person != $matches[1]) {
        $family_members[] = $matches[1] ;
      }
    }
  }

  return $family_members ;
}

/**
 * Removes slashes from names
 */
function gedparse_clean_name($name) {
  $name = str_replace('/', '', $name) ;

  return $name ;
}

/**
 * Removes CONC/CONT tags and connects lines
 */
function gedparse_concatenate($text) {
  $text = preg_replace("/\n\d+? CONC/", " ", $text) ;
  $text = preg_replace("/\n\d+? CONT/", "<br>", $text) ;

  return $text;
}
